version: '3.8'

services:
  web:
    build: .
    command: uvicorn src.app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      FASTAPI_SERVICE_PORT: 8000
      FASTAPI_SERVICE_HOST: 0.0.0.0
      FASTAPI_SERVICE_MONGO_USERNAME: mongoadmin
      FASTAPI_SERVICE_MONGO_PASSWORD: mongoadmin
      FASTAPI_SERVICE_MONGO_HOST: mongo
      FASTAPI_SERVICE_MONGO_PORT: 27017
    env_file:
      - ./.env

  mongo:
    image: mongo:4.1.6
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    env_file:
      - ./.env
